#! /bin/bash
#
# simple init script for gitlab-webhook-receiver
#
#
# chkconfig: 345 99 01
# description: gitlab webhook receiver
#
# File : gitlab-webhook-receiver

### BEGIN INIT INFO
# Provides:          gitlab-webhook-receiver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts gitlab webhook receiver
# Description:       Enable service provided by gitlab-webhook-receiver.
### END INIT INFO

# Source function library.
. /lib/lsb/init-functions

prog="/opt/gitlab-webhook-receiver/gitlab-webhook-receiver.py"
name="gitlab-webhook-receiver"
PROG_USER="puppet"
RETVAL=0

start () {
        echo -n "Starting $prog"
        /usr/bin/sudo -u $PROG_USER "$prog" &
        RETVAL=$?
        [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
        echo
}

stop () {
        echo -n "Stopping $prog"
        /usr/bin/sudo -u $PROG_USER /usr/bin/pkill -2 -f "$prog"
        RETVAL=$?
        [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
        echo
}

restart () {
        stop
        start
}


# See how we are called.
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  status)
        status_of_proc "$prog" "$name"
        RETVAL=$?
        ;;
  *)
        echo "Usage: service gitlab-webhook-receiver {start|stop|restart|reload}"
        RETVAL=2
        ;;
esac

exit $RETVAL
